name: tests

on:
  push:
    branches:      
       - main

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpcs

      - name: start
        run: make start

      - name: linter
        run: make lint